# Oh My Zsh framework
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

# zsh-autocomplete (custom OMZ plugin)
[".oh-my-zsh/custom/plugins/zsh-autocomplete"]
    type = "archive"
    url = "https://github.com/marlonrichert/zsh-autocomplete/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
